// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopDataAccess;

#nullable disable

namespace ShopDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230729224031_foranyupdate")]
    partial class foranyupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopDataModel.Model.PhoneBooking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AvailableDateForCollection")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PhoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeofPayment")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("PhoneBookings");
                });

            modelBuilder.Entity("ShopDataModel.Model.PhoneList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhonePrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhoneLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75cddc4f-50a8-43cd-bcb0-f9cfadc54478"),
                            PhoneModel = "IPhone114pro",
                            PhonePrice = 1000
                        },
                        new
                        {
                            Id = new Guid("4e2dd676-3805-484b-8682-6f99e1f96b46"),
                            PhoneModel = "SmasungGalaxys11",
                            PhonePrice = 1500
                        },
                        new
                        {
                            Id = new Guid("23172592-5eec-4804-ab47-72242cc1cf41"),
                            PhoneModel = "RedmiNote12pro",
                            PhonePrice = 400
                        },
                        new
                        {
                            Id = new Guid("7bb28b8c-ed19-4d19-8245-a531bdeef99e"),
                            PhoneModel = "Iphone13promax",
                            PhonePrice = 1300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
