// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopDataAccess;

#nullable disable

namespace ShopDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230731151030_addedPhonemodel")]
    partial class addedPhonemodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopDataModel.Model.PhoneBooking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AvailableDateForCollection")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PhoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeofPayment")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("PhoneBookings");
                });

            modelBuilder.Entity("ShopDataModel.Model.PhoneList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfStocks")
                        .HasColumnType("int");

                    b.Property<string>("PhoneModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhonePrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhoneLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4b8d672-bc70-43ac-af2b-3e461c58f40a"),
                            NumberOfStocks = 3,
                            PhoneModel = "IPhone114pro",
                            PhonePrice = 1000
                        },
                        new
                        {
                            Id = new Guid("cd580360-46b3-4560-bc55-beece60d1c55"),
                            NumberOfStocks = 2,
                            PhoneModel = "SmasungGalaxys11",
                            PhonePrice = 1500
                        },
                        new
                        {
                            Id = new Guid("197f70e4-c870-4fc6-b5d4-7e4f3bdff3b5"),
                            NumberOfStocks = 4,
                            PhoneModel = "RedmiNote12pro",
                            PhonePrice = 400
                        },
                        new
                        {
                            Id = new Guid("c3cbd403-f457-4dc0-971b-de00b8fb41d3"),
                            NumberOfStocks = 1,
                            PhoneModel = "Iphone13promax",
                            PhonePrice = 1300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
